### ISSUE TITLE
Get current product attribute before updating

### ISSUE THREAD

**Issue by haelbichalex** [bigbridge-nl/product-import#11]
Hi,

This might be more of a feature request, where I'm not even sure if it's a good idea to do this in your importer, but maybe it would be also helpful for someone else.

I'm setting a `custom_publication_date` variable based on 3 different date values, which I get from my import file. For example, if I only get `publication_year`, I set the `custom_publication_date` to `31.12.XXXX`, but when I also get a `publication_month` the value should be `31.XX.XXXX`.
Now that works when creating new products, as I just set the value according to the given values.

But if there's an update for an existing product and I read my import file and notice I delete the `publication_month` for example, I must update my `custom_publication_date` value as well. The problem is I now don't have access to the previous given `publication_year` value now, which the value should be based on.

I was thinking about something like `$product->fetchAttributeData("publication_year")` where we then only fetch this data from the database. Of course this would probably slow down the import a lot, but with great responsibility... 😁 

If you think this is a good idea, let me know as I would then start with the pull request.
An alternative for me would of course be a cron job to set the `custom_publication_date` value based on the current other attribute values.

Regards,
Alex

**Comment by patrick-bigbridge** [comment]
Hi Alex,

I understand your use case, and I appreciate your effort to extend the library, but their are some reasons why I do not want to include the fetching of data (yet).

The most important reason is that fetching attribute data of many products can best be done in a single query. And sometimes you need multiple attributes. Then there are store views to consider. In short, the most efficient way of fetching data differs per use case.

Second, to fetch data of all kinds of product attributes and other aspects is a lot of work. Now we could start by just building what we need, but in order to make this extendible in the future, a new class tree would need to be set up. I don't want to clutter the Product class with fetch methods, it is too far outside of its responsibility.

And last, there is a perfectly good way to fetch some data directly from the database: direct database access. For example in http://blog.chapagain.com.np/magento-2-run-custom-sql-query/

To conclude, currently I am reluctant to include fetching data into the library. If, however, more people need such functionality and the same type of product data requests keep occurring, we could make a exception for some special cases. I would then suggest the class Api/Information for this.

**Comment by haelbichalex** [comment]
For anyone interested: I dealt with my issue by creating a new class and using the `Magento2DbConnection` provided by this project (because why not).
```php
/**
 * @param \BigBridge\ProductImport\Model\Persistence\Magento2DbConnection $dbConnection
 */
public function __construct(
    \BigBridge\ProductImport\Model\Persistence\Magento2DbConnection $dbConnection
) {
    $this->dbConnection = $dbConnection;
}
```

And here I fetch the attributes value:
```php
$this->dbConnection->fetchSingleCell("
    SELECT `value`
    FROM `catalog_product_entity_varchar`
    WHERE `attribute_id` = {$attributeId} AND `entity_id` = {$this->productId}
");
```

This either returns my desired value or null, what tells me I need to do an update.
