### ISSUE TITLE
Bundle setOptionTitle empty

### ISSUE THREAD

**Issue by lucafuse94** [bigbridge-nl/product-import#17]
The method `setOptionTitle` on global Bundle is not working properly, the option title is empty.

**Code example:**
```php
$global->setOptionTitle($option, 'capacity');
```

After further investigation, I have notice that the `parent_product_id` column of  `catalog_product_bundle_option_value` table is set to 0 instead the bundle entity_id.

In `createOptions` method of class `BigBridge\ProductImport\Model\Resource\Storage\BundleStorage` I have solved by adding this:
**original:**
```php
foreach ($product->getStoreViews() as $storeView) {
	foreach ($storeView->getOptionInformations() as $optionInformation) {

		$this->db->execute("
			INSERT INTO `{$this->metaData->bundleOptionValueTable}`
			SET
				`option_id` = ?,
				`store_id` = ?,
				`title` = ?
		", [
			$optionInformation->getOption()->id,
			$storeView->getStoreViewId(),
			$optionInformation->getTitle()
		]);
	}
}
```
**changed:** 
```php
foreach ($product->getStoreViews() as $storeView) {
	foreach ($storeView->getOptionInformations() as $optionInformation) {

		$this->db->execute("
			INSERT INTO `{$this->metaData->bundleOptionValueTable}`
			SET
				`option_id` = ?,
				`store_id` = ?,
				`title` = ?,
				`parent_product_id` = ?
		", [
			$optionInformation->getOption()->id,
			$storeView->getStoreViewId(),
			$optionInformation->getTitle(),
			$product->id,
		]);
	}
}
```

**Comment by garfix** [comment]
Thanks for reporting this bug to me, and for finding the cause! 

Apparently both `catalog_product_bundle_option_value` and `catalog_product_bundle_option` contain a reference to the bundle product. This is atypical for Magento, so this makes me wonder what the reason is of this redundant storage.

I will create a new release that contains your fix shortly. Are you still developing your import code? In that case it may be smart for me to wait to see if you come across some more bugs.

**Comment by garfix** [comment]
I created release 1.4.4 for this issue. 

I also started using a tool ( https://github.com/dlevsha/compalex/ ) to check if the database tables have changed between two releases. This will help me avoid this kind of problem in the future.
