### ISSUE TITLE
Magento 2.4.1 support

### ISSUE THREAD

**Issue by hypershopbv** [bigbridge-nl/product-import#20]
The product importer does not seems to work properly on Magento 2.4.1. Products are not created. Is there 2.4.1 compatibility yet?

**Comment by patrick-bigbridge** [comment]
I haven't checked that yet. Let me get back to you on that in a day or two.

**Comment by hypershopbv** [comment]
Thanks Patrick, i will be waiting for your reply!

**Comment by patrick-bigbridge** [comment]
Ok, I ran my tests on an M2.4.1 implementation and importing still works. Decimals and price fields have changed from 4 decimals to 6 decimals since 2.4.0, but further there are no relevant database changes for product import, I think.

I ran the doc/example/a-basic-product.xml import, adjusting it as needed. Saw no changes. Ran indexer:reindex because I am not running the cronjobs. And then the product appeared.

There are many possible reasons why a product doesn't show up in the webshop; there may be errors (log them) the website may be missing in the import, the category may be missing, the product may not be enabled or not visible, the indexes are not set to 'update by schedule' or the cronjobs may not be running. And there may be rules active that don't allow the customer to view the product. Am I missing something?

Can you please check these? If the products still don't show up, I may need to know more about your import to help you.

**Comment by patrick-bigbridge** [comment]
There found a problem with tier prices, due to change to 6 decimals. Tier prices are not stored properly in M2.4, due to the change of 4 to 6 decimals. I am working on a solution.

**Comment by patrick-bigbridge** [comment]
I published release 1.5.2 to fix the problem with tier prices in M2.4 and added support for 20.6 format price decimals.

@hypershopbv let me know if I can be of help.

**Comment by hypershopbv** [comment]
Thanks Patrick, this works like a charm!
