### ISSUE TITLE
Saving product on storeview scope overwrites storeview attribute values with global values

### ISSUE THREAD

**Issue by IvoJongmans** [bigbridge-nl/product-import#35]
Hi Patrick,

Sorry to bother you again. I just came across this issue. When I've imported a product and I try to edit an attribute value (in my case 'Search Engine Optimization ' -> 'Meta Description') on the storeview level and hit 'Save' the product on the storeview level gets all the same values as the global attributes instead of it's own distinct values. 

I've included a simple .XML that I use for my import. It consists of one product.

[exportProducts.txt](https://github.com/bigbridge-nl/product-import/files/5982221/exportProducts.txt)

Screenshot before saving:

![S1](https://user-images.githubusercontent.com/48712793/107960058-6f721800-6fa4-11eb-95ce-59f5e1a2b5eb.png)

Screenshot after saving: 

![S2](https://user-images.githubusercontent.com/48712793/107960087-7862e980-6fa4-11eb-82be-25bad9c7258b.png)

Maybe you can help me out. Thanks in advance.

**Comment by patrick-bigbridge** [comment]
Is your store by chance still set to 'Enable Single-Store Mode'?

**Comment by IvoJongmans** [comment]
'Enable Single-Store Mode' is set to 'No'

![image](https://user-images.githubusercontent.com/48712793/108033513-64ff5f00-7034-11eb-866a-7c3f5106667c.png)

**Comment by patrick-bigbridge** [comment]
This is quite a strange case, Ivo. But I think I found it.

I was able to reproduce your findings with your xml on a local 2.3.1 implementation. But when I checked it with my default xml import, a-basic-product.xml, I had no such problem.

So bit by bit I started to change your file into my file and see what happened. After a few tries I located the major difference: your xml file _does not contain the website of the product_.

What happens when you forget the website of a product is quite interesting. When you first modify the product via the backend, Magento offers to copy the global values to the store views of all websites:

![product-in-websites](https://user-images.githubusercontent.com/17122199/108111784-79277880-7095-11eb-9ac4-6a7fd020d1c1.png)

You are likely to miss this, because this tab is collapsed by default.

But when Magento copies these values, it just overwrites any existing store view values.

I was even able to reproduce this with a product I created in the backend (no import):

- Create a product, with sku, name, description, price
- Uncheck the websites that are checked by default
- Save
- Change to a store view
- Change the store view values of name and description to something else
- Uncheck the websites that are checked by default
- Save
- Change the store view values of name and description to something else
- Leave the websites checked as is
- Save

The store view now shows the global values again.

This may be considered a bug in Magento, but it is one does not normally occur. As long as you specify a website. :)

**Comment by IvoJongmans** [comment]
Hi,

This solved my issue. Thanks again!
