### ISSUE TITLE
Two slow queries detected

### ISSUE THREAD

**Issue by haelbichalex** [bigbridge-nl/product-import#4]
Hi!

We have a database with around 2.500.000 products and the importer is getting quite slow. No complaining here, just trying to speed the process up again. ☺️ 
I looked into the `Magento2DbConnection.php` class and noticed the `echoSlowQueries` feature, which I used to get the following output (I dumped the `$values` array as well here):
```
0.64743208885193:
            SELECT A.`attribute_code`, O.`option_id`, V.`value`
            FROM eav_attribute A
            INNER JOIN eav_attribute_option O ON O.attribute_id = A.attribute_id
            INNER JOIN eav_attribute_option_value V ON V.option_id = O.option_id
            WHERE A.`entity_type_id` = ? AND A.frontend_input IN ('select', 'multiselect') AND V.store_id = 0

array(1) {
  [0]=>
  string(1) "4"
}
0.6437680721283:
            SELECT A.`attribute_code`, O.`option_id`, V.`value`
            FROM eav_attribute A
            INNER JOIN eav_attribute_option O ON O.attribute_id = A.attribute_id
            INNER JOIN eav_attribute_option_value V ON V.option_id = O.option_id
            WHERE A.`entity_type_id` = ? AND A.frontend_input IN ('select', 'multiselect') AND V.store_id = 0

array(1) {
  [0]=>
  string(1) "4"
}
```

All other queries are below 0.00 seconds. I can't figure out why these queries are so slow here, because the `eav_attribute` tables aren't that big.

Any help is appreciated! 👍

**Comment by patrick-bigbridge** [comment]
Hi!

It's good that you ask. The query that you mention loads all attribute option values into memory. It's executed once every batch (500 products) in OptionResolver::refresh().

I suspect that executing the query mainly takes a lot of time because all option value data has to be transferred from the database to the PHP process. I think you may have hundreds of thousands of option values. If you execute the query in a mysql client (replacing the '?' by 4) you can see.

There are two types of data that the library reloads every batch: category information and option value information. The reason: it is possible that other processes than the library itself change categories and option values while the importer is running. It seemed like a small overhead. Apparently it is not always so.

I am going to think about a good solution for your problem. In the meanwhile, for my information, can you tell me something about your import: what types of products do you import? Do you import mainly simple attributes or more complex ones as well? How many categories? Do you support multiple store views? And how much time does the complete import currently take? I'd like to collect some reference information. :)

**Comment by patrick-bigbridge** [comment]
Thanks for informing me about your import. It helps me to understand your situation better.
You have quite a number of option values, so it takes some time to load them all (I think phpmyadmin adds a limit to the query before executing it). This is reason for me to not load all of them each batch again, but just once. You will still have the slow query (0.6s) once every import, but since it occurs only once this is fine.

I made another change that helps you to import many option values. The library used to create the correct sort_order for each new option. I changed this, because this process takes quite some time (looking up the highest sort_order present for the attribute, in an unindexed column). I fixed this sort order on 10000. This should not cause any problems, but will give some extra speed.

New release is 1.2.3

You may also want to check out [this text](https://github.com/bigbridge-nl/product-import/blob/master/doc/tips.md) I just wrote for some tips to speed up an import.

Just let me know if you have any more problems.

**Comment by patrick-bigbridge** [comment]
@haelbichalex I am just curious how you are doing.

**Comment by haelbichalex** [comment]
@patrick-bigbridge I'm sorry, was quite busy the last weeks. Your change to exec the query only once did the trick for me 👍 Successfully importing all my products in ~30 hours, so I'm closing this issue.

Thank you for your awesome work!
