### ISSUE TITLE
Updating products results in database error

### ISSUE THREAD

**Issue by HS-Fachmarkt** [bigbridge-nl/product-import#9]
Hello.
I'am trying to use your importer for periodically mass updating our about 16000 Products.

Basically, i use this code (sku is already in use):
$product = new \BigBridge\ProductImport\Api\Data\SimpleProduct($sku);
$this->importer->importSimpleProduct($product);
$this->importer->flush();

This results in:
- SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entity_id' in 'field list'
- duplicate entry in the database table catalog_product_entity (row_id and dates are different from the original entry)

Could you give me a hint, whats wrong here?

Magento Version: 2.3 Commerce

**Comment by garfix** [comment]
Hello!

Since you mention you are using Magento Commerce, I think this may be the problem. I developed the library for Magento Opensource and I haven't had access to Magento Commerce so I cannot provide support for it, I'm afraid. 

Since this is a low-level library, it writes directly to MySQL tables. If there is any difference between the database structure of Opensource and Commerce, and I am certain there is, changes would have to be made.

greetings,
Patrick

**Comment by antoninobonumore** [comment]
I can confirm that this plugin is not compatible with Magento Commerce 2.3

**Comment by patrick-bigbridge** [comment]
Magento Commerce has a sufficiently different database table structure from Open Source to allow a quick adjustment. That's why I don't plan to support Magento Commerce in the near future.
